version: "2"
services:
    django:
        image:
            0bara/django
        ports:
            - 8000:8000
        working_dir: "/opt/projects"
        command: 
            python manage.py runserver 0.0.0.0:8000
            #django-admin.py startproject --template ./template ${PRJ} .
        volumes:
            - web:/opt/projects

volumes:
    web:
        driver_opts:
            type: none
            device: $PWD/projects
            o: bind
